#!/bin/bash
# Blockhost Server Initialization Script
# Generates server keypair and creates initial configuration
#
# Usage: sudo ./scripts/init-server.sh [--decrypt-message "custom message"]

set -euo pipefail

# Configuration
CONFIG_DIR="/etc/blockhost"
DATA_DIR="/var/lib/blockhost"
TERRAFORM_DIR="/opt/blockhost/terraform"
PROXMOX_TERRAFORM_DIR="/opt/blockhost/proxmox-terraform"

PRIVATE_KEY_FILE="${CONFIG_DIR}/server.key"
CONFIG_FILE="${CONFIG_DIR}/blockhost.yaml"

# Default decrypt message (can be overridden via --decrypt-message)
DECRYPT_MESSAGE="blockhost-access"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --decrypt-message)
            DECRYPT_MESSAGE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--decrypt-message \"custom message\"]"
            echo ""
            echo "Options:"
            echo "  --decrypt-message   Static message users sign to derive encryption key"
            echo "                      Default: \"blockhost-access\""
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Check root
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Check pam_web3_tool is available
if ! command -v pam_web3_tool &> /dev/null; then
    echo "Error: pam_web3_tool not found. Install libpam-web3-tools package."
    exit 1
fi

echo "========================================"
echo "  Blockhost Server Initialization"
echo "========================================"
echo ""

# Create directories
echo "Creating directories..."
mkdir -p "${CONFIG_DIR}"
mkdir -p "${DATA_DIR}"
mkdir -p "${TERRAFORM_DIR}"
mkdir -p "${PROXMOX_TERRAFORM_DIR}"

# Check if already initialized
if [[ -f "${PRIVATE_KEY_FILE}" ]]; then
    echo ""
    echo "WARNING: Server keypair already exists at ${PRIVATE_KEY_FILE}"
    read -p "Regenerate keypair? This will invalidate existing encrypted data. [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing keypair."

        # Still show the public key
        PRIVATE_KEY=$(cat "${PRIVATE_KEY_FILE}")
        PUBLIC_KEY=$(pam_web3_tool derive-pubkey --private-key "${PRIVATE_KEY}" | grep -oP '(?<=hex\): ).*')

        echo ""
        echo "========================================"
        echo "  Existing Server Public Key"
        echo "========================================"
        echo ""
        echo "Public key (for signup page):"
        echo "${PUBLIC_KEY}"
        echo ""
        exit 0
    fi
fi

# Generate keypair
echo "Generating secp256k1 keypair..."
PRIVATE_KEY=$(pam_web3_tool generate-keypair | grep -oP '(?<=hex\): ).*')

# Save private key (restricted permissions)
echo "${PRIVATE_KEY}" > "${PRIVATE_KEY_FILE}"
chmod 600 "${PRIVATE_KEY_FILE}"
echo "Private key saved to: ${PRIVATE_KEY_FILE}"

# Derive public key
PUBLIC_KEY=$(pam_web3_tool derive-pubkey --private-key "${PRIVATE_KEY}" | grep -oP '(?<=hex\): ).*')

# Create/update config file
echo "Creating configuration..."
cat > "${CONFIG_FILE}" << EOF
# Blockhost Server Configuration
# Generated by init-server.sh on $(date -Iseconds)

# Static message users sign to derive their encryption key
# This must match what the signup page displays
decrypt_message: "${DECRYPT_MESSAGE}"

# Server public key (for reference - signup page needs this)
# Private key is stored in: ${PRIVATE_KEY_FILE}
server_public_key: "${PUBLIC_KEY}"
EOF

chmod 644 "${CONFIG_FILE}"
echo "Configuration saved to: ${CONFIG_FILE}"

# Initialize empty VM database if it doesn't exist
DB_FILE="${DATA_DIR}/vms.json"
if [[ ! -f "${DB_FILE}" ]]; then
    echo "Initializing VM database..."
    cat > "${DB_FILE}" << EOF
{
  "vms": {},
  "next_vmid": 100,
  "next_nft_token_id": 0,
  "allocated_ips": []
}
EOF
    chmod 644 "${DB_FILE}"
    echo "VM database created: ${DB_FILE}"
fi

echo ""
echo "========================================"
echo "  Initialization Complete"
echo "========================================"
echo ""
echo "Server Public Key (configure in signup page):"
echo "${PUBLIC_KEY}"
echo ""
echo "Decrypt Message (display on signup page):"
echo "${DECRYPT_MESSAGE}"
echo ""
echo "Files created:"
echo "  - ${PRIVATE_KEY_FILE} (chmod 600)"
echo "  - ${CONFIG_FILE}"
echo "  - ${DB_FILE}"
echo ""
echo "Next steps:"
echo "  1. Configure signup page with the public key above"
echo "  2. Deploy proxmox-terraform scripts to ${PROXMOX_TERRAFORM_DIR}"
echo "  3. Configure Terraform in ${TERRAFORM_DIR}"
echo "  4. Start the blockhost-monitor service"
echo ""
